### ISSUE TITLE
Keras and TF version

### ISSUE THREAD

**Issue by zhanghanduo** [mpkuse/cerebro#1]
Hi. Thank you for your work. However, it takes quite some effort to make your code work.

It seems your documentation can be improved. The dependency Theia-sfm requires oiio and RocksDB which are not mentioned, and oiio requires OpenExr and all these dependencies are quite heavy.

Could you also provide the version of TF and keras you have used? Is it 1.08? Thank you again!

**Comment by mpkuse** [comment]
Hi, Thanks for pointing out the additional dependencies for theia-sfm. 

I am using TF1.11 and Keras 2.2.2 and Keras 2.2.4. However in general tf1.08 should also be fine. 

I recommend using my code with docker.

**Comment by zhanghanduo** [comment]
Thanks for the info. Using docker should be convenient. It seems you are using json serializor. I haven't used it before. I have been using cereal for my serialization tasks.
Your cerebro seems promising. I will give my feedbacks after I can make it run. :)

**Comment by mpkuse** [comment]
FYI, with some efforts the dependence on theia-sfm can be removed. I use it to compute the relative because, the PnP from it was more stable than the one from OpenCV. So if from theia-sfm the PnP code can be isolated (I know for a fact that it can be done). 

Sure handuo, let me know how it works for you.
