### ISSUE TITLE
new branches of robust-pose-computation

### ISSUE THREAD

**Issue by MoonUniverse** [mpkuse/cerebro#18]
hello,
Thanks for your great work again! Recently I noticed that you updated a new branch of robust-pose-computation,I am curious about it's use and some performance improvements.Do you have a simple description of this later?

thanks!

**Comment by mpkuse** [comment]
So, currently I am okish with the place recognition part, in the sense it can reasonably identify places. However the weak-spot is the pose computation part (after identifying loop candidates). 

So, with this branch, I am moving to detection of loop-hypothesis-sequences rather than loop-candidate-pairs. See https://github.com/mpkuse/cerebro/blob/7a8df59c55937c04b9d13b0b546ccf2e8090f67f/src/Cerebro.cpp#L735 and src/HypothesisManager.h 

And I am implementing pose computation from sequences, which potentially uses nearby frames for a more robust pose computation. https://github.com/mpkuse/cerebro/blob/7a8df59c55937c04b9d13b0b546ccf2e8090f67f/src/Cerebro.cpp#L1584 

However, it is not complete yet. Keep tuned for my updates. Also will be happy if you develop something to this effect.

**Comment by MoonUniverse** [comment]
Thanks for your reply! 
I will keeping learning! thanks.
